version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp
    container_name: myapp_container
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - myapp_network

  webserver:
    image: nginx:alpine
    container_name: nginx_container
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - myapp_network

  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cromos_cuestionarios
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - myapp_network

networks:
  myapp_network:
    driver: bridge
